id: P000589
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:48:44.572379
source_metadata:
  id: bdr:W1KG23134
  title: འཇུག་ཊཱིཀ་དྭགས་བརྒྱུད་གྲུབ་པའི་ཤིང་རྟ།
  author: ''
  volumes:
    80576604f1da485a9b1247e9a51f80bb:
      image_group_id: I1KG23493
      title: ''
      volume_number: 1
      total_pages: 502
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
