id: P000589
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23134
  title: འཇུག་ཊཱིཀ་དྭགས་བརྒྱུད་གྲུབ་པའི་ཤིང་རྟ།
  author: ''
  volumes:
    61bd70ccc4864632ad18f80c2ce1bbbe:
      image_group_id: I1KG23493
      title: ''
      volume_number: 1
      total_pages: 502
