id: IA12E14A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T18:16:00+00:00'
last_modified: '2022-06-07T12:23:54.914936+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23134
  title: འཇུག་ཊཱིཀ་དྭགས་བརྒྱུད་གྲུབ་པའི་ཤིང་རྟ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AF19:
      image_group_id: I1KG23493
      title: ''
      total_pages: 502
      order: 1
      base_file: AF19.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
